[package]
name = "btp-utp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand            = "0.3.0"
num-traits      = "0.1"
log             = { version = "0.4.0", features = ["std"] }

