[package]
name = "bittorrent-client-demo"
version = "0.1.0"
authors = ["xinwater <1872407021@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
